name: "Build & Deploy Tileserver"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Github Container registry
  REGISTRY: us-central1-docker.pkg.dev
  REGISTRY_PATH: ${{ secrets.GCP_PROJECT }}/tileserver
  SERVICE_NAME: tileserver
  GCP_REGION: us-central1

jobs:
  prod-build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx2-

      - name: Configure Docker Credentials
        shell: bash
        run: gcloud auth configure-docker -q ${{ env.REGISTRY }}

      - name: Build & Push tileserver
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color -var="services_tag=${{ github.sha }}"
        working-directory: terraform

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
